# setup vars
environ:                        "stage" # dev || stage || prod
login_user_passphrase:          "{{ vault_login_user_passphrase }}"

# assetstore vars
remote_stores_available:        false
# stores_fstab:             "sam.mse.jhu.edu:/apps/dspace_snapshot"
# /dev/sdc1                                       /mnt/assetstore xfs             defaults        0 0
stores_fstab:
- name:   "/mnt/dspace/storage"
  src:    "/dev/sdc1"
  fstype: "xfs"
  opts:   "defaults"
  state:  "absent"
# - name:   "/mnt/assetstore"
#   src:    "/dev/sdc1"
#   fstype: "xfs"
#   opts:   "defaults"
#   state:  "absent"

# db vars
dspace_db_address:              "psql02.{{ domainname }}"
