# setup vars
environ:                        "stage" # dev || stage || prod

# assetstore vars
remote_stores_available:    false
stores_fstab:
- name:   "/mnt/dspace/storage"
  src:    "sam.mse.jhu.edu:/apps/dspace_snapshot"
  fstype: "nfs"
  opts:   "rw,tcp,intr,noatime"
  state:  "absent"
# - name:   "/mnt/dspace/storage"
#   src:    "/dev/sdc1"
#   fstype: "xfs"
#   opts:   "defaults"
#   state:  "absent"
# - name:   "/mnt/assetstore"
#   src:    "/dev/sdc1"
#   fstype: "xfs"
#   opts:   "defaults"
#   state:  "absent"

# apache vars
dspace_name:                    "JScholarship-{{ environ | title }}"
ssl_certificate_file:           "{{ vault_ssl_certificate_file }}"
ssl_certificate_key_file:       "{{ vault_ssl_certificate_key_file }}"
ssl_certificate_chain_file:     "{{ vault_ssl_certificate_chain_file }}"
PASS_config:                    false

# db vars
dspace_db_address:              "psql02.{{ domainname }}"
db_transform_queries:           []

# upgrade vars
dspace_backup_statistics: false

# temporary debugging values
loglevel_dspace:  "INFO" # DEBUG, INFO, WARN, ERROR, FATAL
email_disabled:   true
