# setup vars
environ:                        "prod" # dev || stage || prod

# assetstore vars
remote_stores_available:        true
stores_fstab:
- name:   "/mnt/dspace/storage"
  src:    "sam.mse.jhu.edu:/apps/dspace"
  fstype: "nfs"
  opts:   "rw,tcp,intr,noatime"
  state:  "mounted"

# apache vars
ssl_certificate_file:           "{{ vault_ssl_certificate_file }}"
ssl_certificate_key_file:       "{{ vault_ssl_certificate_key_file }}"
ssl_certificate_chain_file:     "{{ vault_ssl_certificate_chain_file }}"
# hostname:                       "jscholarship"
# domainname:                     "library.jhu.edu"
PASS_config:                    true
ssl_support_legacy_clients:     true

# db vars
dspace_db_address:              "psql03.mse.jhu.edu"

# config vars
# NOTE: comment dspace_hostname_override out if PASS_config is false
dspace_hostname_override:       "jscholarship.library.jhu.edu"
dspace_mail_admin:              "jscholarship-help@jhu.edu"
