# REM: if you are looking for passwords or other variables
# that vary from dev to stage to prod, check the other subfolders

# setup vars
project:        "jscholarship"
version:        "0.1.0"
login_user:     "deploy"

# testing vars
set_up_tests:   true

# application user vars - dspace user and tomcat user
app_user:       "dspace"

# install vars
dspace_major_version: 5
dspace_minor_version: 8
dspace_version:       "{{ dspace_major_version }}.{{ dspace_minor_version }}"
dspace_install_dir:   "/opt"
dspace_install:       "{{ dspace_install_dir }}/dspace"
dspace_user_home:     "/home/{{ app_user }}"
dspace_source_dir:    "dspace-{{ dspace_version }}"
dspace_source:        "{{ dspace_user_home }}/{{ dspace_source_dir }}"

# apache vars
dspace_name:            "JScholarship"
hostname:               "{{ dspace_name | lower }}"
domainname:             "library.jhu.edu"
apache_https:           true
apache_proxy_tomcat:    true

# db vars
db_password:            "{{ vault_db_password }}"
db_name:                "dspace"
db_user:                "dspace"
db_create_users:        true
db_users:
  - user:               "{{ db_user }}"
    pass:               "{{ db_password }}"
    flags:              "NOSUPERUSER"

db_create_databases:    true
db_databases:
  - name:               "{{ db_name }}"
    encoding:           "UTF-8"
    owner:              "{{ db_user }}"

postgres_hba_entries:
- type:                 "host"
  database:             "{{ db_name }}"
  user:                 "{{ db_user }}"
  address:              "{{ dspace_address }}"
  method:               "md5"

# vars for branding
# -----------------
logo_blue:    "002D72" #	PMS 288C
medium_blue:  "005EB8" # PMS 300C
blue_grey:    "A7BCD6" #	PMS 651C
logo:         "sheridan-libraries.logo.small.horizontal.white.svg"

# assetstore vars
remote_stores_available: false
stores_fstab:             ""
assetstores:
  - assetstore
  - assetstore1

# config vars
# TODO: set http://jhir.library.jhu.edu/handle/ for prod?
# dspace_handle_canonical_prefix: "{{ dspace_fqdn }}/handle/"
dspace_handle_prefix:     1774.2
helpdesk_override:        true
# TODO: set true for prod
use_proxies:              false
bulk_edit_limit:          500

# logging vars
# TODO: incorporate logrotate
loglevel_default: "WARN"
loglevel_dspace:  "{{ loglevel_default }}"
loglevel_solr:    "{{ loglevel_default }}"
loglevel_other:   "{{ loglevel_default }}"
max_logs: 14
log_dir: "{{ dspace_install }}/log"
