- name: install dspace prereqs
  hosts: app

  roles:
  - { role: java, jdk: true,  tags: ['java'],         become: true }
  - { role: maven,            tags: ['maven'] }
  - { role: ant,              tags: ['ant'] }
  - { role: tomcat,           tags: ['tomcat'] }
  - { role: apache,           tags: ['apache'] }
  - { role: imagemagick,      tags: ['imagemagick'],  become: true }
  - { role: psi-probe,        tags: ['psi-probe'],    become: true }
