- name: install dspace prereqs
  hosts: app

  roles:
  - { role: java, jdk: true,  tags: ['java'],   become: true }
  - { role: maven,            tags: ['maven'] }
  - { role: ant,              tags: ['ant'] }
