- name: get facts from db server (e.g. ip), for the app server's config
  hosts: db
  gather_facts: true

- name: install dspace
  hosts: app

  tasks:
  - include_role:
      name: dspace-5
    tags: ['dspace']
    when: dspace_major_version == 5

  - include_role:
      name: dspace-6
    tags: ['dspace']
    when: dspace_major_version == 6
